
# global configuration
version: 1.0.4
pull_requests:
    do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2017
build_script:
- ps: ./build.ps1
#notifications:
#- provider: GitHubPullRequest
#      on_build_success: true
#      on_build_failure: true
#      on_build_status_changed: true


for:
# configuration for master branch
-
  branches:
    only:
      - master
  version: {version}.{build}
  dotnet_csproj:
      patch: true
      file: '**\*.csproj'
      version: '{version}'
      package_version: '{version}'
      assembly_version: '{version}.{build}'
      file_version: '{version}.{build}'
      informational_version: '{version}'
  environment:
      branch: master
  
        
# configuration for develop branch
-
  branches:
    only:
      - develop
  version: {version}-preview-{build}
  dotnet_csproj:
      patch: true
      file: '**\*.csproj'
      version: '{version}-preview1-{build}'
      package_version: '{version}-preview1-{build}'
      assembly_version: '{version}'
      file_version: '{version}'
      informational_version: '{version}-preview1-{build}'
  environment:
      branch: develop
        
# configuration for all other branches
-
  version: {version}-build-{build}
  environment:
      branch: none

