
#notifications:
#- provider: GitHubPullRequest
#    on_build_success: true
#    on_build_failure: true
#    on_build_status_changed: true

ver: 1.0.4

# configuration for master branch
-
  branches:
    only:
      - master
  version: '{ver}.{build}'
  pull_requests:
      do_not_increment_build_number: true
  skip_tags: true
  image: Visual Studio 2017
  dotnet_csproj:
      patch: true
      file: '**\*.csproj'
      version: '{ver}'
      package_version: '{ver}'
      assembly_version: '{ver}.{build}'
      file_version: '{ver}.{build}'
      informational_version: '{ver}'
  environment:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      branch: master
  cache: '%USERPROFILE%\.nuget\packages'
  build_script:
  - ps: ./build.ps1
        
# configuration for develop branch
-
  branches:
    only:
      - develop
  version: '{ver}'
  pull_requests:
      do_not_increment_build_number: true
  skip_tags: true
  image: Visual Studio 2017
  dotnet_csproj:
      patch: true
      file: '**\*.csproj'
      version: '{ver}-preview1-{build}'
      package_version: '{ver}-preview1-{build}'
      assembly_version: '{ver}'
      file_version: '{ver}'
      informational_version: '{ver}-preview1-{build}'
  environment:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      branch: develop
  cache: '%USERPROFILE%\.nuget\packages'
  build_script:
  - ps: ./build.ps1
        
# configuration for all other branches
-
  version: {ver}-preview1-{build}
  pull_requests:
      do_not_increment_build_number: true
  skip_tags: true
  image: Visual Studio 2017
  environment:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      branch: none
  cache: '%USERPROFILE%\.nuget\packages'
  build_script:
  - ps: ./build.ps1